/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package trees;

import Data.Node;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

//        BinerySearchTree binerySearchTree= new BinerySearchTree();
//
//        binerySearchTree.add(2);
//        binerySearchTree.add(3);
//        binerySearchTree.add(4);
//        binerySearchTree.add(5);
//        System.out.println("contains !!"+ binerySearchTree.contains(10));
//
        BineryTree bineryTree= new BineryTree();

        bineryTree.setRoot(new Node(1));
        bineryTree.getRoot().setLeft(new Node(2));
        bineryTree.getRoot().setRight(new Node(3));
        bineryTree.getRoot().getLeft().setLeft(new Node(4));
        bineryTree.getRoot().getLeft().setRight(new Node(5));
        bineryTree.inOrder(bineryTree.getRoot());
    }
}
