/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Linkedlist;


public class Library {
    public boolean someLibraryMethod() {
        return true;
    }


    public String getGreeting() {
        return "Hello World!";
    }
    public static void main(String[] args){


        LinkedList linked =new LinkedList();
//        linked.insert(10);
//        linked.insert(20);
//        linked.insert(30);
//        linked.insert(40);
//        linked.insert(50);
//        System.out.println(linked.insertBefore(20,5));

        linked.append(3);
        linked.append(2);
        linked.append(2);
        linked.append(2);
        linked.append(1);
//        System.out.println(linked.palindrome());
//
//        LinkedList linked4 =new LinkedList();

//                System.out.println("the node is "+linked.returnNum(2));
        LinkedList linked2 =new LinkedList();
        linked2.append(-60);
        linked2.append(-70);
        linked2.append(-80);
        LinkedList linked3 =new LinkedList();
//        System.out.println(linked2.toString());
//
//
        System.out.println(linked3.mergeTwoLists(linked,linked2));
//
//


//        linked.insertBefore(40,5);
//
        System.out.println(linked);
        System.out.println(linked.include(20));
        System.out.println(linked.toString());
//        LinkedList list = new LinkedList();
//        list.add(2);
//        list.add(5);
        



    }

}
