/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Linkedlist;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

public class LibraryTest {

    @Test void appHasAGreeting() {
        Library classUnderTest = new Library();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

    LinkedList list = new LinkedList();

    @Test void testEmptyList(){
        String result = list.toString();
        assertEquals("Null",result);
    }
//    LinkedList linked = new LinkedList();
    @Test void testInsert(){
        list.insert(10);

        String expect = list.toString();
        assertEquals("Must be {10} ->Null","{10} ->Null" ,expect);
    }

//    @Test void testInclude(){
//        linked.insert(10);
//        linked.insert(20);
//        linked.insert(30);
//        linked.insert(40);
//        linked.insert(50);
//        int expect = 20;
//        boolean x=linked.include(20);
//        assertEquals(expect ,x);
//    }


//    @Test void kGreaterLength() {
//        linked.insert(2);
//        linked.append(4);
//        linked.append(3);
//        linked.append(5);
//        int expect = -1 ;
//        int x=  linked.returnNum(5);
//        assertEquals(expect ,x);
//    }
//    @Test void kEqualLength(){
//        linked.insert(2);
//        linked.append(4);
//        linked.append(3);
//        linked.append(5);
//        int expect = 2;
//        int x=  linked.returnNum(4);
//        assertEquals(expect,x);
//    }
//    @Test void negativeK(){
//        linked.insert(2);
//        linked.append(4);
//        linked.append(3);
//        linked.append(5);
//        int expect = 0;
//        int x=  linked.returnNum(-1);
//        assertEquals(expect,x);
//    }
//    @Test void oneNode(){
//        linked.insert(5);
//        int expect = 5;
//        int x=  linked.returnNum(1);
//        assertEquals(expect,x);
//    }
//    @Test void happyPath(){
//        linked.insert(2);
//        linked.append(4);
//        linked.append(9);
//        linked.append(6);
//        linked.append(8);
//        int expect = 9;
//        int x=  linked.returnNum(3);
//        assertEquals(expect,x);
//    }
}
