package stack.and.queue;/*
 * This Java source file was generated by the Gradle 'init' task.
 */

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

//        Stack stack=new Stack();
//        Queue queue=new Queue();
//        stack.push(4);
//        stack.push(5);
//        stack.push(6);
//        stack.push(7);
////        stack.pop();
//        stack.tostring();
//
//        queue.enQueue(4);
//        queue.enQueue(5);
//        queue.enQueue(6);
//        queue.enQueue(7);
//        System.out.println("front"+ queue.peek());
//        queue.tostring();


        PseudoQueue sodo = new PseudoQueue();
        sodo.enqueue(1);
        sodo.enqueue(2);
        sodo.enqueue(3);
        sodo.dequeue();
        sodo.tostring();
    }
}
